import type { Metadata } from "next";
import "./globals.css";
import UserNavbar from "@/components/UserNavbar";
import BottomBar from "@/components/bottomBar";
import { Toaster } from "react-hot-toast";
 
export const metadata: Metadata = {
  title: "Date in Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return 
    <html lang="en">
      <body>
         <Toaster />
        <UserNavbar />
        {children}
        <BottomBar/>
      </body>
    </html>
  ;
}
