import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast"; 
import { Poppins } from "next/font/google";
import BottomBar from "@/components/bottomBar";
import UserNavbar from "@/components/UserNavbar";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });


export const metadata: Metadata = {
  title: "Date-in",
  description: "Generated by Date-in",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` relative ${inter.className}`  } >
          <Toaster />
          <div className="   w-full min-h-screen ">
            <UserNavbar/>
            {children}
            <BottomBar/>
          </div>
      </body>
    </html>
  );
}
